---
title: "Scatterplot"
output: html_notebook
runtime: shiny
---

La représentation standard de la relation entre deux variables continues, chacune représentée par un axe. 

```{r echo=TRUE, message=FALSE, warning=FALSE}
require(xlsx) # Permet de lire des fichier xls
require(httr) # Permet de faire des requêtes http
require(altair) # Permet d'utiliser Vega-Lite
```

On importe les données
```{r echo=TRUE, message=FALSE, warning=FALSE}

# Depuis le site de l'insee
URL="https://insee.fr/fr/statistiques/fichier/2521169/base_cc_comparateur.zip"

#on les télecharge et on les dézip
temp <- tempfile()
download.file(URL,temp)
xls<-unzip(temp, "base_cc_comparateur.xls")
unlink(temp)

#on sélectionne les variables qui nous intéressent (ici les 10 premières)
col<-c("character",  "character", "character", "character","integer","integer" ,"integer" ,"integer" ,"integer" ,"integer"  )

donnees_scatterplot <- read.xlsx2(xls, 1, startRow = 6, endRow = 5000, header=TRUE, colClasses=col, colIndex = 1:10)
```

On sauvegarde les données pour une utilisation ultérieure.
```{r echo=TRUE}
filename <- paste(dirname(dirname(dirname(rstudioapi::getSourceEditorContext()$path))),"/Data/Scatterplot.Rdata", sep = "")
save(donnees_scatterplot, file = filename)
```


On construit ensuite l'objet vegalite ...
```{r echo=TRUE}
scatterplot <- 
  alt$Chart(na.omit(donnees_scatterplot))$
  mark_point()$
  encode(
    x = alt$X('DECE1015:Q', axis=alt$Axis(title="Décès entre 2010 et 2015")),
    y = alt$Y('NAIS1015:Q', axis=alt$Axis(title="Naissances entre 2010 et 2015")),
    color = alt$Color('REG:N', legend=alt$Legend(title="Régions")),
    tooltip = c("LIBGEO","DECE1015", "NAIS1015", "REG")
    )$
  properties(
    title = "Scatterplot"
  )#$interactive()
  
#NB : Sur altair (python), il existe une limite d'observations (5000 max). Je ne sais pas si elle s'applique aussi en R, je n'aipas pu tester le graphique. 
```


On affiche le graphique
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=TRUE}
scatterplot
```

On obtient le schéma JSON correspondant.
```{r echo=TRUE}
scatterplot$to_json()
```