---
title: "Column + line Timeline"
output: html_notebook
runtime: shiny
---

Un bon moyen de montrer la relation entre une quantité (colonnes) et un taux (ligne).

```{r echo=TRUE, message=FALSE, warning=FALSE}
require(XML) # Permet de lire des fichier html
require(httr) # Permet de faire des requêtes http
require(altair) # Permet d'utiliser Vega-Lite
```

On importe les données
```{r echo=TRUE, message=FALSE, warning=FALSE}

# Depuis le site de l'insee
URL <- "https://www.insee.fr/fr/statistiques/fichier/1892086/pop-totale-france.xls"

#On les importe
GET(URL, write_disk(tf <- tempfile(fileext = ".html")))
donnees <- readHTMLTable(tf, which = 1,
                         header = TRUE,
                         skip.rows = c(1, 2, 3, 4, 5, 107,108, 109),
                         encoding="UTF-8",
                         stringsAsFactors = FALSE,
                         colClasses = c("character", "integer", "character", "character", "character", "character"))

donnees_finales <- data.frame(Ensemble = as.integer(gsub(" ", "", donnees$Ensemble, fixed = TRUE)), Age_revolu = donnees$`Âge révolu`,nb_femmes=as.integer(gsub(" ", "", donnees$`Nombre de femmes`, fixed = TRUE)),nb_hommes=as.integer(gsub(" ", "", donnees$`Nombre d'hommes`, fixed = TRUE)))

donnees_finales$femme<-'Femmes'
donnees_finales$homme<-'Hommes'
```


On construit ensuite l'objet vegalite ...
```{r echo=TRUE}
point <- alt$Chart(donnees_finales)$mark_point()$encode(
  y=alt$Y('nb_femmes:Q'),
  x=alt$X('Age_revolu:Q'),
  color=alt$Color('femme:N',
                  legend=alt$Legend(title="Efectifs hommes/femmes"),
                  scale=alt$Scale(
                    domain=c('Femmes','Hommes'),
                    range=c('red','green')
                  )
                 ),
  tooltip = c("Age_revolu:Q","nb_femmes:Q")
)
```

```{r echo=TRUE}
point2 <- alt$
  Chart(donnees_finales)$
  mark_point()$encode(
    y=alt$Y('nb_hommes:Q'),
    x=alt$X('Age_revolu:Q'),
    color=alt$Color(
      'homme:N',
      scale=alt$Scale(
        domain=c('Hommes', 'Femmes'),
        range=c('green', 'red')
      )
    ),
  tooltip = c("Age_revolu:Q","nb_hommes:Q")
)
```

```{r echo=TRUE}
bar <- alt$
  Chart(donnees_finales)$
  mark_bar()$
  encode(
    x = alt$X('Age_revolu:Q',
              axis = alt$Axis(title="Age"),
              bin = alt$Bin(maxbins = 20)
             ),
    y = alt$Y('Ensemble:Q',
              axis = alt$Axis(title="Population totale en 2018")
             ),
    tooltip = c("Age_revolu:Q","Ensemble:Q")
)
```

```{r echo=TRUE}
chart <- (bar + point + point2)$properties(title="Column + line timeline")
```


On affiche le graphique
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=TRUE}
chart
```

On obtient le schéma JSON correspondant.
```{r echo=TRUE}
chart$to_json()
```
