---
title: "XY heatmap"
output: html_notebook
runtime: shiny
---

Un bon moyen de montrer les tendances entre 2 catégories de données, moins bon pour montrer de fines différences de quantités. 

```{r echo=TRUE, message=FALSE, warning=FALSE}
require(xlsx) # Permet de lire des fichier xls
require(httr) # Permet de faire des requêtes http
require(altair) # Permet d'utiliser Vega-Lite
#install_altair(pip = T)
```

On importe les données
```{r echo=TRUE, message=FALSE, warning=FALSE}

# Depuis le site de l'insee
URL="https://insee.fr/fr/statistiques/fichier/2521169/base_cc_comparateur.zip"

#on les télecharge et on les dézip
temp <- tempfile()
download.file(URL,temp)
xls<-unzip(temp, "base_cc_comparateur.xls")
unlink(temp)

#on sélectionne les variables qui nous intéressent (ici les 10 premières)
c1<-c("character",  "character", "character", "character","integer","integer" ,"integer" ,"integer" ,"integer" ,"integer"  )
c2<-rep("NULL",26)
col <- c(c1,c2)

data<-read.xlsx2(xls, 1,startRow = 6, header=TRUE, colClasses=col)
```


On construit ensuite l'objet vegalite ...
```{r echo=TRUE}
heatmap <- alt$Chart(data)$mark_rect()$encode(    
    x=alt$X('DECE1015:Q', axis=alt$Axis(title="Décès entre 2010 et 2015")),
    y=alt$Y('NAIS1015:Q', axis=alt$Axis(title="Naissances entre 2010 et 2015")),
    color=alt$Color('P15_POP:Q', legend=alt$Legend(title="Population en 2015")),
    tooltip=["LIBGEO","DECE1015", "NAIS1015", "REG","P15_POP"]
)$
  properties(
    title = "XY Heatmap"
  )#$interactive()
 
#NB : Sur altair (python), il existe une limite d'observations (5000 max). Je ne sais pas si elle s'applique aussi en R, je n'aipas pu tester le graphique. 

#NB2 : pas très intéressant sur ces données.
```


On affiche le graphique
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=TRUE}
heatmap
```

On obtient le schéma JSON correspondant.
```{r echo=TRUE}
heatmap$to_json()
```