---
title: "Paired column"
output: html_notebook
runtime: shiny
---

# Paired column


```{r echo=TRUE, message=FALSE, warning=FALSE}
require(xlsx) # Permet de lire des fichier xls
require(httr) # Permet de faire des requêtes http
require(altair) # Permet d'utiliser Vega-Lite
```

Importation des données
```{r echo=TRUE, message=FALSE, warning=FALSE}

# Lien des données depuis le site de l'Insee
URL="https://insee.fr/fr/statistiques/fichier/3682672/if138.xls"

# Téléchargement
GET(URL, write_disk(tf <- tempfile(fileext = ".xls")))
```

Traitement des données
```{r echo=TRUE, message=FALSE, warning=FALSE}
# on garde les variables utiles : les deux premières et les variations annuelles
col<-c("character", "numeric", "numeric")

donnees_paired_col <- read.xlsx2(tf, 1, startRow = 7, endRow = 24, header=TRUE, colClasses=col, colIndex = c(1,4,7))

names(donnees_paired_col)[1] <- "Region"
names(donnees_paired_col)[2] <- "Variation 2011-2016"
names(donnees_paired_col)[3] <- "Variation 2006-2011"

donnees_finales = data.frame(matrix(vector(), 34, 3,
                dimnames=list(c(), c("Region", "Periode", "Variation"))),
                stringsAsFactors=T)



for (i in 0:16){
  donnees_finales$Region[2*i+1] <- donnees_paired_col$Region[i+1]
  donnees_finales$Region[2*(i+1)] <- donnees_paired_col$Region[i+1]
  donnees_finales$Periode[2*i+1] <- "2006-2011"
  donnees_finales$Periode[2*(i+1)] <- "2011-2016"
  donnees_finales$Variation[2*i+1] <- donnees_paired_col$`Variation 2006-2011`[i+1]
  donnees_finales$Variation[2*(i+1)] <- donnees_paired_col$`Variation 2011-2016`[i+1]
}

```


Construction du graphique
```{r echo=TRUE}

title_X <- "Variation annuelle"
title_Y <- "Periode"

paired_bar <- alt$
              Chart(donnees_finales)$
              mark_bar()$
              encode(
                x = alt$X('Variation:Q', axis = alt$Axis(title = title_X, orient = "top")),
                y = alt$Y('Periode:O', axis = NULL),
                row = "Region:N",
                color = alt$Color('Periode:N')
                
              )$
              properties(
                title = "Paired bar"
              )
```

Affichage du graphique
```{r echo=TRUE, message=FALSE, warning=FALSE}
paired_bar
```